# Exploración de Datos: 1DATABASE1.csv

Este notebook tiene como objetivo explorar y describir las columnas del archivo **1DATABASE1.csv**,
así como presentar los valores típicos de cada variable (media, mínimo, máximo, desviación estándar, etc.).

In [19]:
import pandas as pd # Importar la libreria

In [33]:
df = pd.read_csv("https://raw.githubusercontent.com/cquiroz2011/ML-EDUCACION/refs/heads/main/PROYECTO/1DATABASE1.csv", sep=';')  #lectura de dataset a trabajar

## Descripción de las columnas

- **Nombre**: Identificador del estudiante.
- **Nota 1**: Primera calificación parcial en Biología. Formato decimal con coma (ej. 5,5).
- **Nota 2**: Segunda calificación parcial.
- **Asistencia Clases (%)**: Porcentaje de asistencia a clases teóricas.
- **Asistencia Laboratorio (%)**: Porcentaje de asistencia a sesiones de laboratorio.
- **APROBADO/REPROBADO**: Variable cualitativa que indica si el estudiante aprobó o reprobó la asignatura.

In [34]:
# Convertir notas de texto con coma a float
df['Nota 1'] = df['Nota 1'].astype(str).str.replace(',', '.').astype(float)
df['Nota 2'] = df['Nota 2'].astype(str).str.replace(',', '.').astype(float)

In [35]:
# Estadísticas básicas
df.describe(include='all')

,Nombre,Nota 1,Nota 2,PROMEDIO,Unnamed: 4,Asistencia Clases (%),Asistencia Laboratorio (%),Unnamed: 7,APROBADO/REPROBADO
count,30,30.000000,30.000000,30,0.0,30.000000,30.000000,0.0,30
unique,30,NaN,NaN,15,NaN,NaN,NaN,NaN,2
top,Estudiante 1,NaN,NaN,"4,7",NaN,NaN,NaN,NaN,APROBADO
freq,1,NaN,NaN,4,NaN,NaN,NaN,NaN,25
mean,NaN,4.703333,4.823333,NaN,NaN,86.933333,82.300000,NaN,NaN
std,NaN,1.269940,1.264552,NaN,NaN,7.759014,9.660263,NaN,NaN
min,NaN,3.000000,3.000000,NaN,NaN,66.000000,60.000000,NaN,NaN
25%,NaN,3.525000,3.700000,NaN,NaN,82.500000,75.250000,NaN,NaN
50%,NaN,4.550000,4.950000,NaN,NaN,86.500000,81.500000,NaN,NaN
75%,NaN,5.850000,5.775000,NaN,NaN,90.000000,89.000000,NaN,NaN
max,NaN,6.800000,6.900000,NaN,NaN,99.000000,100.000000,NaN,NaN